'use client';

import { useEffect, useState } from 'react';
import type { NewsItem } from '@/data/news';
import { getAssetPath } from '@/lib/basePath';
import type { Language } from '@/lib/i18n/LanguageProvider';

// Per-language news content is fetched from public/news/{lang}.json
// (generated by scripts/generate-news-data.js) instead of statically
// imported from @/data/news — that file bundles all 6 languages (~450KB)
// into the client JS of every "use client" component that imports it,
// including NewsPreview on the homepage. Fetching only the active
// language keeps that payload to a single language's slice (~55-90KB).
const cache: Partial<Record<Language, NewsItem[]>> = {};

const withResolvedImages = (items: NewsItem[]): NewsItem[] =>
  items.map((item) => ({
    ...item,
    images: item.images.map((img) => getAssetPath(`/images/${img}`)),
  }));

export function useNewsData(language: Language): NewsItem[] | null {
  const [data, setData] = useState<NewsItem[] | null>(
    cache[language] ?? null,
  );

  useEffect(() => {
    const cached = cache[language];
    if (cached) {
      setData(cached);
      return;
    }
    let cancelled = false;
    fetch(getAssetPath(`/news/${language}.json`))
      .then((res) => res.json())
      .then((items: NewsItem[]) => {
        if (cancelled) return;
        const resolved = withResolvedImages(items);
        cache[language] = resolved;
        setData(resolved);
      });
    return () => {
      cancelled = true;
    };
  }, [language]);

  return data;
}
